# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opt.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'opt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\topt.proto\"B\n\x13OptimizationRequest\x12\x14\n\x03w_i\x18\x01 \x03(\x0b\x32\x07.Matrix\x12\x15\n\x04ww_j\x18\x02 \x03(\x0b\x32\x07.Matrix\"=\n\x14OptimizationResponse\x12\t\n\x01x\x18\x01 \x03(\x02\x12\t\n\x01y\x18\x02 \x03(\x02\x12\x0f\n\x07success\x18\x03 \x01(\x08\"2\n\x06Matrix\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x03 \x01(\x05\x32W\n\x13OptimizationService\x12@\n\x11SolveOptimization\x12\x14.OptimizationRequest\x1a\x15.OptimizationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIMIZATIONREQUEST']._serialized_start=13
  _globals['_OPTIMIZATIONREQUEST']._serialized_end=79
  _globals['_OPTIMIZATIONRESPONSE']._serialized_start=81
  _globals['_OPTIMIZATIONRESPONSE']._serialized_end=142
  _globals['_MATRIX']._serialized_start=144
  _globals['_MATRIX']._serialized_end=194
  _globals['_OPTIMIZATIONSERVICE']._serialized_start=196
  _globals['_OPTIMIZATIONSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
